# ========== Profile ========== #
# avatar
avatar: /avatar/zane.jpg
# author name
author: Zane
# signature
signature:
  愿我一生欢喜, 
  不为世俗所及
# SNS (you can custom the order)
social:
  wechat: /assets/wechat.png
  qq: /assets/qq.png
  github: https://github.com/qinglong
  weibo: https://weibo.com/p/1005055206925677/home?from=page_100505&mod=TAB#place
  bilibili:
  email: qinglong@kooboo.cn
  # wechat and qq should be a path of qr-code image
  telegram: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  segmentFault: 
  juejin: 
  v2ex: 
  linkedin: 
  steam: 
  others: 
  rss: 
# friends
friends:
  friendA: 
  friendB: 
  friendC: 
about:
  enable: true
  image: '/intro/country.jpg'

# ========== Site ========== #
# title of the site (good for SEO)
SEO_title:
# keywords for site (good for SEO)
SEO_keywords:
  - Zane
  - Blog
  - 'hexo-theme'
  - 'hexo-blog'
# main title shown in header image
main_title: "Zane's blog"
home_link: Home
# subtitle
subtitle: Doing is better than saying
# site haeder image
site_header_image: '/intro/about.jpg'
# random bg
# site_header_image: https://bing.ioliu.cn/v1/rand?w=2560&h=1440

# post haeder image
post_header_image: '/intro/about-bg.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Search ========== #
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We did not find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: MTAyMC80ODc5OC8yNTI5Mg==
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 
  # Valine  site: https://valine.js.org/
  valine_appId: 
  valine_appKey: 
  valine_placeHolder: 

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: true
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} :)'
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /assets/icon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# word count & reading time
reading_info: false
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
# copyright
copyright:
  enable: false
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
